name: portfolio
description: A personal portfolio of Karimul Hasan made using Flutter!.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  animated_text_kit: ^4.2.1
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_animation_progress_bar: ^2.0.1
  flutter_dotenv: ^5.0.2
  flutter_emoji: ^2.4.0
  flutter_svg: ^0.23.0+1
  font_awesome_flutter: ^9.2.0
  get: ^4.3.8
  get_it: ^7.2.0
  lottie: ^1.2.2
  parse_server_sdk_flutter: ^3.1.0
  provider: ^6.0.1
  rive: ^0.8.4
  timeline_tile: ^2.0.0
  url_launcher: ^6.0.20
  url_strategy: ^0.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/
    - images/surecare/
    - images/utmccta/
    - images/shopper/
    - images/chatty/
    - images/todos/
    - images/coviddetector/
    - images/armario/
    - images/erp_mobile/
    - images/fingertips/
    - images/passgen/
    - images/surecareadmin/
    - images/surecarereviewer/
    - images/erp_web/
    - svg/
  fonts:
    - family: Courier New
      fonts:
        - asset: fonts/CourierNewBold.ttf
        - asset: fonts/CourierNew.ttf
